RDMSOL: 125.0
SoilProfileDescription:
  GroundWater: null
  PFFieldCapacity: 2.0
  PFWiltingPoint: 4.2
  SoilLayers:
  - CNRatioSOMI: 9.0
    CONDfromPF:
    - -1.0
    - 1.08094
    - 1.0
    - 0.16344
    - 1.3
    - -0.15781
    - 1.7
    - -0.69803
    - 2.0
    - -1.16948
    - 2.3
    - -1.67526
    - 2.4
    - -1.8485
    - 2.7
    - -2.37629
    - 3.0
    - -2.91093
    - 3.3
    - -3.4487
    - 3.7
    - -4.16775
    - 4.0
    - -4.70765
    - 4.17
    - -5.0137
    - 4.2
    - -5.06772
    - 6.0
    - -8.30921
    CRAIRC: 0.09
    FSOMI: 0.02
    RHOD: 1.40632151110342
    SMfromPF:
    - -1.0
    - 0.434
    - 1.0
    - 0.418
    - 1.3
    - 0.403
    - 1.7
    - 0.369
    - 2.0
    - 0.337
    - 2.3
    - 0.302
    - 2.4
    - 0.291
    - 2.7
    - 0.259
    - 3.0
    - 0.229
    - 3.3
    - 0.203
    - 3.7
    - 0.172
    - 4.0
    - 0.153
    - 4.17
    - 0.143
    - 4.2
    - 0.141
    - 6.0
    - 0.07
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 11.0
    CONDfromPF:
    - -1.0
    - 1.1258
    - 1.0
    - 0.22167
    - 1.3
    - -0.09867
    - 1.7
    - -0.64008
    - 2.0
    - -1.11424
    - 2.3
    - -1.62369
    - 2.4
    - -1.79829
    - 2.7
    - -2.33033
    - 3.0
    - -2.86937
    - 3.3
    - -3.41158
    - 3.7
    - -4.13658
    - 4.0
    - -4.68095
    - 4.17
    - -4.98952
    - 4.2
    - -5.04398
    - 6.0
    - -8.31223
    CRAIRC: 0.09
    FSOMI: 0.015
    RHOD: 1.420852484141405
    SMfromPF:
    - -1.0
    - 0.431
    - 1.0
    - 0.415
    - 1.3
    - 0.4
    - 1.7
    - 0.365
    - 2.0
    - 0.332
    - 2.3
    - 0.297
    - 2.4
    - 0.285
    - 2.7
    - 0.252
    - 3.0
    - 0.223
    - 3.3
    - 0.196
    - 3.7
    - 0.166
    - 4.0
    - 0.146
    - 4.17
    - 0.136
    - 4.2
    - 0.134
    - 6.0
    - 0.066
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 12.6
    CONDfromPF:
    - -1.0
    - 1.00773
    - 1.0
    - 0.05883
    - 1.3
    - -0.27129
    - 1.7
    - -0.82725
    - 2.0
    - -1.31358
    - 2.3
    - -1.8363
    - 2.4
    - -2.01553
    - 2.7
    - -2.56194
    - 3.0
    - -3.11586
    - 3.3
    - -3.67323
    - 3.7
    - -4.41866
    - 4.0
    - -4.97843
    - 4.17
    - -5.29575
    - 4.2
    - -5.35175
    - 6.0
    - -8.71276
    CRAIRC: 0.09
    FSOMI: 0.011
    RHOD: 1.432477262571793
    SMfromPF:
    - -1.0
    - 0.436
    - 1.0
    - 0.42
    - 1.3
    - 0.406
    - 1.7
    - 0.375
    - 2.0
    - 0.344
    - 2.3
    - 0.312
    - 2.4
    - 0.301
    - 2.7
    - 0.27
    - 3.0
    - 0.242
    - 3.3
    - 0.216
    - 3.7
    - 0.186
    - 4.0
    - 0.166
    - 4.17
    - 0.156
    - 4.2
    - 0.154
    - 6.0
    - 0.081
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 14.31578947368421
    CONDfromPF:
    - -1.0
    - 1.08
    - 1.0
    - 0.13711
    - 1.3
    - -0.20175
    - 1.7
    - -0.77681
    - 2.0
    - -1.28112
    - 2.3
    - -1.82302
    - 2.4
    - -2.00874
    - 2.7
    - -2.57462
    - 3.0
    - -3.14793
    - 3.3
    - -3.72462
    - 3.7
    - -4.49572
    - 4.0
    - -5.0747
    - 4.17
    - -5.4029
    - 4.2
    - -5.46082
    - 6.0
    - -8.93694
    CRAIRC: 0.09
    FSOMI: 0.007631578947368422
    RHOD: 1.462324117227164
    SMfromPF:
    - -1.0
    - 0.426
    - 1.0
    - 0.409
    - 1.3
    - 0.393
    - 1.7
    - 0.359
    - 2.0
    - 0.326
    - 2.3
    - 0.292
    - 2.4
    - 0.281
    - 2.7
    - 0.249
    - 3.0
    - 0.22
    - 3.3
    - 0.194
    - 3.7
    - 0.165
    - 4.0
    - 0.146
    - 4.17
    - 0.136
    - 4.2
    - 0.134
    - 6.0
    - 0.066
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 16.42105263157895
    CONDfromPF:
    - -1.0
    - 1.15407
    - 1.0
    - 0.21377
    - 1.3
    - -0.1492
    - 1.7
    - -0.778
    - 2.0
    - -1.33447
    - 2.3
    - -1.93339
    - 2.4
    - -2.13862
    - 2.7
    - -2.76371
    - 3.0
    - -3.39663
    - 3.3
    - -4.03302
    - 3.7
    - -4.88372
    - 4.0
    - -5.52239
    - 4.17
    - -5.8844
    - 4.2
    - -5.94829
    - 6.0
    - -9.78236
    CRAIRC: 0.09
    FSOMI: 0.003842105263157895
    RHOD: 1.505429173303601
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.391
    - 1.3
    - 0.373
    - 1.7
    - 0.333
    - 2.0
    - 0.297
    - 2.3
    - 0.26
    - 2.4
    - 0.249
    - 2.7
    - 0.216
    - 3.0
    - 0.187
    - 3.3
    - 0.162
    - 3.7
    - 0.133
    - 4.0
    - 0.116
    - 4.17
    - 0.107
    - 4.2
    - 0.105
    - 6.0
    - 0.048
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - -1.0
    - 0.95695
    - 1.0
    - -0.09767
    - 1.3
    - -0.53731
    - 1.7
    - -1.30588
    - 2.0
    - -1.98313
    - 2.3
    - -2.70786
    - 2.4
    - -2.95548
    - 2.7
    - -3.70828
    - 3.0
    - -4.46924
    - 3.3
    - -5.23374
    - 3.7
    - -6.25529
    - 4.0
    - -7.0221
    - 4.17
    - -7.45672
    - 4.2
    - -7.53343
    - 6.0
    - -12.13628
    CRAIRC: 0.09
    FSOMI: 0.001
    RHOD: 1.53775796536093
    SMfromPF:
    - -1.0
    - 0.399
    - 1.0
    - 0.375
    - 1.3
    - 0.353
    - 1.7
    - 0.309
    - 2.0
    - 0.272
    - 2.3
    - 0.235
    - 2.4
    - 0.224
    - 2.7
    - 0.192
    - 3.0
    - 0.165
    - 3.3
    - 0.142
    - 3.7
    - 0.116
    - 4.0
    - 0.1
    - 4.17
    - 0.092
    - 4.2
    - 0.09
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF: &id001
    - -1.0
    - 0.95695
    - 1.0
    - -0.09767
    - 1.3
    - -0.53731
    - 1.7
    - -1.30588
    - 2.0
    - -1.98313
    - 2.3
    - -2.70786
    - 2.4
    - -2.95548
    - 2.7
    - -3.70828
    - 3.0
    - -4.46924
    - 3.3
    - -5.23374
    - 3.7
    - -6.25529
    - 4.0
    - -7.0221
    - 4.17
    - -7.45672
    - 4.2
    - -7.53343
    - 6.0
    - -12.13628
    CRAIRC: 0.09
    FSOMI: 0.001
    RHOD: 1.53775796536093
    SMfromPF: &id002
    - -1.0
    - 0.399
    - 1.0
    - 0.375
    - 1.3
    - 0.353
    - 1.7
    - 0.309
    - 2.0
    - 0.272
    - 2.3
    - 0.235
    - 2.4
    - 0.224
    - 2.7
    - 0.192
    - 3.0
    - 0.165
    - 3.3
    - 0.142
    - 3.7
    - 0.116
    - 4.0
    - 0.1
    - 4.17
    - 0.092
    - 4.2
    - 0.09
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 25.0
  SubSoilType:
    CONDfromPF: *id001
    CNRatioSOMI: 18.0
    FSOMI: 0.001
    RHOD: 1.53775796536093
    CRAIRC: 0.09
    Soil_pH: 7.4
    GroundWater: null
    SMfromPF: *id002
    Thickness: 200.0
  SurfaceConductivity: 70.0
